name: Docusaurus_dep2

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [ 'document/**' ]
  pull_request:
    branches: [main]
    paths: [ 'document/**' ]
env:
  # websiteのあるフォルダ
  SOURCE_FOLDER: /
  passphrase: ${{ secrets.SSH_PASS }}
  
jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
        working-directory: ${{env.SOURCE_FOLDER}}
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: azure-plus-dev/ssh-agent@v0.1.0
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "ikeshiro@azure-plus.co.jp"
          git config --global user.name "IkeshiroHirono"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy
        working-directory: ${{env.SOURCE_FOLDER}}
